= SDK API Specification


== API Version

// tag::api-version[]
This release of the SDK is written to version {sdk_api} of the SDK API specification (and matching the features available in Couchbase {server_version} and earlier).
For most developers, just using the latest version will be all that matters, and few will need to look at another of our SDKs.
Just for those few that do, the table below shows each Couchbase SDK release version that matches the API version.

Whilst these two numbers match for the .NET and Ruby SDKs, this is not the case for the others, as version numbers for individual SDKs are bumped up in line with https://semver.org/[Semantic Versioning] -- check the xref:sdk-release-notes[release notes] of each SDK for individual details.

.SDK API Versions
[cols="30,20,20,23,21,20,20"]
|===
| | API 3.0 | API 3.1 | API 3.2 | API 3.3 | API 3.4 | API 3.5

| C (libcouchbase)
| 3.0
| 3.1
| 3.2
| 3.3.0 - 3.3.2
| 3.3.3 footnote:[]
| N/A footnote:[ ]

| .NET
| 3.0
| 3.1
| 3.2
| 3.3
| 3.4
| 3.5

| Go
| 2.0 & 2.1
| 2.2
| 2.3 & 2.4
| 2.5
| 2.6 & 2.7
| 2.8

| Java
| 3.0
| 3.1
| 3.2
| 3.3
| 3.4 & 3.5
| 3.6

| Kotlin
| -
| -
| -
| 1.0
| 1.1 & 1.2
| 1.3

| Node.js
| 3.0
| 3.1
| 3.2 & 4.0
| 4.1
| 4.2
| 4.3

| PHP
| 3.0
| 3.1
| 3.2
| 4.0
| 4.1
| 4.2

| Python
| 3.0
| 3.1
| 3.2
| 4.0
| 4.1
| 4.2

| Ruby
| 3.0
| 3.1
| 3.2
| 3.3
| 3.4
| 3.5

| Scala
| 1.0
| 1.1
| 1.2
| 1.3
| 1.4 & 1.5
| 1.6
|===

<1> Excludes DNS SRV refresh support in Serverless Environments.
<2> For most purposes better productivity and functionality can be found in our
https://github.com/couchbaselabs/couchbase-cxx-client/[{cpp} SDK], currently in Developer Preview.

*SDK API 3.5*: Introduced support for Vector Search alongside Server 7.6 (and Capella).
Adds scoped indexes to Search (for Vector Seach and traditional FTS).
Read from Replica for Query and Sub-Doc operations.
KV Range Scan for querying documents through the Data Service, even if you don't know the document IDs (for use cases that require relatively low concurrency and tolerate relatively high latency).
Transactions now implemented as a native library in all SDKs (except libcouchbase).

*SDK API 3.4*: Introduced support for ARM v8 on Ubuntu 20.04, Transactions on Spring Data Couchbase, and compatibility with running in serverless environments, such as AWS λ.
The `couchbase2://` connection string was introduced in Go 2.7, Java 3.5, Kotlin 1.2, and Scala 1.5, for Cloud Native Gateway with xref:operator::overview.adoc[Couchbase Autonomous Operator] (from CAO 2.6.1).

*SDK API 3.3*: Introduced alongside Couchbase Server 7.1,
adds Management API for Eventing and Index Management for Scopes & Collections;
extends Bucket Management API to support Custom Conflict Resolution and Storage Options;
adds new platform support for Linux Alpine OS, Apple M1, and AWS Graviton2;
provides improved error messages for better error handling;
and an upgraded Spark Connector that runs on Spark 3.0 & 3.1 Platform.

*SDK API 3.2*: Introduced alongside Couchbase Server 7.0,
provides features in support of Scopes and Collections,
extends capabilities around Open Telemetry API to instrument telemetry data,
enhanced client side field level encryption to add an additional layer of security to protect sensitive data,
adds new platform support such as Ubuntu 20.04 LTS.

*SDK API 3.1*: Introduced alongside Couchbase Server 6.6,
focuses on Bucket Management API,
adds capabilities around Full Text Search features such-as Geo-Polygon support, Flex Index, and Scoring. 

*SDK API 3.0*: Introduced alongside Couchbase Server 6.5, is a major overhaul from its predecessor,
has simplified surface area, removed long-standing bugs and deprecated/removed old API,
introduces new programming languages Scala and Ruby,
written in anticipation to support Scopes and Collections.
// end::api-version[]
