= SDK API Specification


== API Version

// tag::api-version[]
This release of the SDK is written to version {sdk_api} of the SDK API specification (and matching the features available in Couchbase {server_version} and earlier).
For most developers, just using the latest version will be all that matters, and few will need to look at another of our SDKs.
Just for those few that do, the table below shows each Couchbase SDK release version that matches the API version (and a table that covers the earliest versions of the 3.x SDK API can be found in documentation for earlier versions of the SDK).

Whilst these two numbers match for the .NET SDK, this is not the case for the others, as version numbers for individual SDKs are bumped up in line with https://semver.org/[Semantic Versioning] -- check the xref:sdk-release-notes[release notes] of each SDK for individual details.

.SDK API Versions
[cols="30,23,21,20,20,20,20"]
|===
| | API 3.3 | API 3.4 | API 3.5 | API 3.6 | API 3.7| API 3.8

| xref:dotnet-sdk:hello-world:overview.adoc[.NET]
| 3.3
| 3.4
| 3.5
| 3.6
| 3.7
| 3.8

| xref:c-sdk:hello-world:overview.adoc[C (libcouchbase)]
| 3.3.0 - 3.3.2
a| 3.3.3 ①
a| N/A ②
a| N/A ②
a| N/A ②
a| N/A ②

| xref:cxx-sdk:hello-world:overview.adoc[{cpp}]
| -
| -
| -
| 1.0
| 1.1
| 1.2

| xref:go-sdk:hello-world:overview.adoc[Go]
| 2.5
| 2.6 & 2.7
| 2.8
| 2.9
| 2.10
| 2.11

| xref:java-sdk:hello-world:overview.adoc[Java]
| 3.3
| 3.4 & 3.5
| 3.6
| 3.7
| 3.8
| 3.9

| xref:kotlin-sdk:hello-world:overview.adoc[Kotlin]
| 1.0
| 1.1 & 1.2
| 1.3
| 1.4
| 1.5
| 3.9 ③

| xref:nodejs-sdk:hello-world:overview.adoc[Node.js]
| 4.1
| 4.2
| 4.3
| 4.4
| 4.5
| 4.6

| xref:php-sdk:hello-world:overview.adoc[PHP]
| 4.0
| 4.1
| 4.2
| 4.2.2
| 4.3
| 4.4

| xref:python-sdk:hello-world:overview.adoc[Python]
| 4.0
| 4.1
| 4.2
| 4.3
| 4.4
| 4.5

| xref:ruby-sdk:hello-world:overview.adoc[Ruby]
| 3.3
| 3.4
| 3.5
| 3.5.2
| 3.6
| 3.7

| xref:scala-sdk:hello-world:overview.adoc[Scala]
| 1.3
| 1.4 & 1.5
| 1.6
| 1.7
| 1.8
| 3.9 ③
|===

<1> Excludes DNS SRV refresh support in Serverless Environments.
<2> For most purposes better productivity and functionality can be found in our
xref:cxx-sdk:hello-world:overview.adoc[{cpp} SDK].
<3> With the Java 3.9 release, the other JVM SDKs hosted in the Java SDK monorepo adopted common release versions.
This includes a number of other artifacts, as can be seen referenced in the release notes.

*SDK API 3.8*: Introduced alongside Couchbase Server 8.0, which adds support for 128 vBuckets on Magma.







*SDK API 3.7*:  Introduced  support for KV reads from preferred server groups.
The .NET SDK has been updated to support the latest Transactions specification -- and the library is now incorporated within the .NET SDK.
A new `getMulti()` interface batch reads with read committed isolation.
Additionally, the Java SDK now includes a Quarkus extension with GraalVM support.

*SDK API 3.6*: Introduced support for base 64 encoded vector types alongside Server 7.6.2 (and Capella).
General Availability of our {cpp} SDK --
now available as a supported, stand-alone SDK, this SDK is also the core of our Node.js, PHP, Python, and Ruby SDKs.

// Zone-aware Read-from-Replica is supported for some SDKs.
// Binary transactions support in some SDKs.
// 

*SDK API 3.5*: Introduced support for Vector Search alongside Server 7.6 (and Capella).
Adds scoped indexes to Search (for Vector Seach and traditional FTS).
Read from Replica for Query and Sub-Doc operations.
KV Range Scan for querying documents through the Data Service, even if you don't know the document IDs (for use cases that require relatively low concurrency and tolerate relatively high latency).
Transactions now implemented as a native library in all SDKs (except libcouchbase).

*SDK API 3.4*: Introduced support for ARM v8 on Ubuntu 20.04, Transactions on Spring Data Couchbase, and compatibility with running in serverless environments, such as AWS λ.
The `couchbase2://` connection string was introduced in Go 2.7, Java 3.5, Kotlin 1.2, and Scala 1.5, for Cloud Native Gateway with xref:operator::overview.adoc[Couchbase Autonomous Operator] (from CAO 2.6.1).

*SDK API 3.3*: Introduced alongside Couchbase Server 7.1,
adds Management API for Eventing and Index Management for Scopes & Collections;
extends Bucket Management API to support Custom Conflict Resolution and Storage Options;
adds new platform support for Linux Alpine OS, Apple M1, and AWS Graviton2;
provides improved error messages for better error handling;
and an upgraded Spark Connector that runs on Spark 3.0 & 3.1 Platform.

*SDK API 3.2*: Introduced alongside Couchbase Server 7.0,
provides features in support of Scopes and Collections,
extends capabilities around Open Telemetry API to instrument telemetry data,
enhanced client side field level encryption to add an additional layer of security to protect sensitive data,
adds new platform support such as Ubuntu 20.04 LTS.

*SDK API 3.1*: Introduced alongside Couchbase Server 6.6,
focuses on Bucket Management API,
adds capabilities around Full Text Search features such-as Geo-Polygon support, Flex Index, and Scoring. 

*SDK API 3.0*: Introduced alongside Couchbase Server 6.5, is a major overhaul from its predecessor,
has simplified surface area, removed long-standing bugs and deprecated/removed old API,
introduces new programming languages Scala and Ruby,
written in anticipation to support Scopes and Collections.
// end::api-version[]
