= User Authentication



// concept-docs common files


// tag::rbac[]
Couchbase uses Role Base Access Control (RBAC), and has since Server 5.0 was released.
For a general overview of Couchbase-Server authorization, see xref:7.1@server:learn:security/authorization-overview.adoc[Authorization].
For a list of available roles and corresponding privileges, see xref:7.1@server:learn:security/roles.adoc[Roles].

In the SDK docs, many examples will use the full _Administrator_ role for convenience, but this is rarely a good idea on a production machine, so reference the above links to find best practice for the needs of your application.
RBAC is also implemented by the Community Edition of Couchbase Server, but with fewer roles -- see the xref:7.1@server:learn:security/roles.adoc[Roles overview].
// end::rbac[]


// tag::cert-auth[]
== Certificate Authentication


Couchbase Server supports the use of X.509 certificates to authenticate clients (only available in the Enterprise Edition, not the Community Edition).
This allows authenticated users to access specific resources by means of the data service, in Couchbase Server 5.1 and up, and all other services in more recent releases of Couchbase Data Platform.

The process relies on a certificate authority, for the issuing of certificates that validate identities.
A certificate includes information such as the name of the entity it identifies, an expiration date, the name of the authority that issued the certificate, and the digital signature of the authority.
A client attempting to access Couchbase Server can present a certificate to the server, allowing the server to check the validity of the certificate.
If the certificate is valid, the user under whose identity the client is running, and the roles assigned that user, are verified.
If the assigned roles are appropriate for the level of access requested to the specified resource, access is granted.

For a more detailed conceptual description of using certificates, see xref:7.1@server:learn:security/certificates.adoc[Certificates].

// end::cert-auth[]


// tag::ldap[]
== LDAP

If you are on a network where access is controlled by LDAP, the SDK will work transparently with it.
Please pay attention to the following important note on secure connection.

[IMPORTANT]
If xref:7.1@server:manage:manage-security/configure-ldap.adoc#understanding-ldap-authentication[LDAP] is enabled, Couchbase Server will only allow PLAIN sasl authentication which by default, for good security, the SDK will not allow.
Although this can be overridden in a development environment, by explicitly enabling PLAIN in the password authenticator, _the secure solution_ is xref:managing-connections.adoc#ssl[to use TLS].

// end::ldap[]
