= Deployment


// tag::intro[]
One of Couchbase's strengths is speedy response, so deployment of apps should be in the same region as the Server -- whether Capella, or your own self-managed cluster.

We always recommend the xref::sdk-release-notes.adoc#latest-release[latest version] of the SDK. 
This not only contains the latest security updates and bug fixes, but will be compatible with the latest Couchbase Server release
(note, Capella always runs a recent version of Couchbase Server).

Before deploying, take note of any xref:compatibility.adoc[compatibility] issues for the language platform and underlying OS.
The xref:sdk-full-installation.adoc[full installation guide] should cover any special cases for all supported environments.
// end::intro[]



// tag::load-balancer[]
[TIP]
.No Load Balancer Required
====
Your Couchbase cluster will take care of balancing the load and distribution of data between nodes,
in tandem with the SDK's use of the cluster map.
A load balancer would negatively affect this work -- 
so the use of a load balancer between your app server, where you're running the SDK and client code, and your Couchbase operational cluster, 
is strongly discouraged.
====
// end::load-balancer[]



// tag::testing[]
During development, some shortcuts are taken to get up and running which would not be acceptable during deployment.
These include use of administrator permissions, connecting from your laptop instead of a secure app server, and even disabling certificate verification for TLS.
Testing environments may also differ from deployment.

The {name-sdk} docs note whenever a shortcut is being taken, but here is a non-exhaustive list of those development practices which should not be carried over to production deployments:

* Over-priveleged access
* Geographical separation of app server and database
* Skipping certificate verification
// end::testing[]



// tag::further-reading[]
== Further Reading

* Integrate Couchbase with your data ecosystem:
** xref:project-docs:third-party-integrations.adoc[SDK Integrations]
** xref:server:develop:integrations.adoc[Integrations across Couchbase]
* xref:project-docs:get-involved.adoc[Contribute to the SDK] 

=== Deploying Couchbase Server

* xref:cloud::index.adoc[Capella] -- Database as a Service
* xref:{version-server}@server:install:get-started.adoc[Self-managed Couchbase Server]:
** xref:{version-server}@server:install:getting-started-docker.adoc[Docker Install]
** xref:operator::overview.adoc[Couchbase Autonomous Operator]
*** xref:operator::install-kubernetes.adoc[Kubernetes]
*** xref:operator::install-openshift.adoc[Openshift]
** xref:{version-server}server:cloud:couchbase-cloud-deployment.adoc[Cloud Marketplace]:
*** xref:{version-server}@server:cloud:couchbase-aws-marketplace.adoc[AWS Marketplace]
*** xref:{version-server}@server:cloud:couchbase-azure-marketplace.adoc[Azure Marketplace]
*** xref:{version-server}@server:cloud:couchbase-gcp-cloud-launcher.adoc[GCP Marketplace]
// end::further-reading[]
