= Interface Stability Paragraphs

[#interface-stability-section]
// tag::interface-stability-section[]
== Interface Stability

[#interface-stability-par]
// tag::interface-stability-par[]
Couchbase SDKs indicate the stability of an API through documentation.
Since there are different meanings when developers mention stability, we mean *interface stability*: how likely the interface is to change or be removed entirely.
A stable interface is one that is guaranteed not to change between versions, meaning that you may use an API of a given SDK version and be assured that the given API will retain the same parameters and behavior in subsequent versions.
An unstable interface is one which may appear to work or behave in a specific way within a given SDK version, but may change in its behavior or arguments in future SDK versions, causing odd application behavior or compiler/API usage errors.
*Implementation stability* is implied to be more reliable at higher levels, but all are tested to the level that is appropriate for their stability.
// end::interface-stability-par[]

Couchbase uses three interface stability classifiers.
You may find these classifiers appended as annotations or comments within documentation for each API:

* *Committed*: This stability level is used to indicate the most stable interfaces that are guaranteed to be supported and remain stable between SDK versions.
* *Uncommitted*: This level is used to indicate APIs that are _unlikely_ to change, but _may_ still change as final consenus on their behavior has not yet been reached.
_Uncommitted_ APIs usually end up becoming stable APIs.
* *Volatile*: This level is used to indicate experimental APIs that are still in flux and may likely be changed.
It may also be used to indicate inherently private APIs that may be exposed, but "YMMV" (your mileage may vary) principles apply.
_Volatile_ APIs typically end up being promoted to _Uncommitted_ after undergoing some modifications.
* *Internal*: This level is used to indicate you should not rely on this API as it is not intended for use outside the module, even to other Couchbase components.

APIs that are marked as _Committed_ have a stable implementation.
_Uncommitted_ and _Volatile_ APIs should be stable within the bounds of any known and often documented issues, but Couchbase has not made a commitment to these APIs and may not respond to reported defects with the same priority.
// end::interface-stability-section[]
