= Collecting Information and Logging







== SDK Telemetry from the Server


// tag::telemetry[]
In addition to Tracing and other metrics, and client logging, SDK telemetry is also sent to the Server -- available from 8.0, and in new Capella Operational clusters -- for ingestion with other Prometheus metrics.
Capella Operatioal exposes these metrics through the UI.

For self-managed Server, collection can be disabled and enabled through the REST API:

[source,console]
----
curl --user Administrator:password http://172.17.0.2:8091/settings/appTelemetry -d enabled=true
----

And the Prometheus-format metrics fetched with:

[source,console]
----
curl --user Administrator:password http://172.17.0.2:8091/metrics
----

Further details can be found in the xref:{version-server}@server:rest-api:application-telemetry.adoc[] page.

There may be advantages to collecting information this way,
but note that metrics are collected per node,
and a central Prometheus instance should be set to collect all metrics so that information is not lost in case of a sudden failover.

Also note that if the cluster is behind a load balancer, the collected metrics may not accurately record the actual correct node with which the SDK interacts.
// end::telemetry[]
