= Managing Connections



== Cloud Native Gateway

// tag::cng[]
Couchbase's next generation connection protocol, is compatible with recent versions of xref:operator:ROOT:concept-cloud-native-gateway.adoc[Couchbase Autonomous Operator] (running on Kubernetes or OpenShift),
or xref:cloud-native-gateway:intro:about-cng.adoc[installed alongside self-managed Server].
The protocol implements a gRPC-style interface between the SDK and Couchbase Server.

It can be enabled by changing the connection string to `couchbase2://` but there are a few differences to be aware of, described <<#limitations,below>>.
// end::cng[]



=== Limitations

// tag::cng-limitations[]
The underlying protocol will not work with certain legacy features: MapReduce Views (a deprecated Service -- 
use xref:howtos:n1ql-queries-with-sdk.adoc[Query] instead) and 
Memcached buckets (superseded by the improved xref:{server_version}@server:learn:buckets-memory-and-storage/buckets.adoc#bucket-types[Ephemeral Buckets]).

The following are not currently implemented over the `couchbase2://` protocol:

* Authentication by client certificate.
* Multi-document ACID transactions.
* Analytics service.
* Health Check.

And the output from these features should be seen as volatile and subject to change:

* Metrics and tracing, including the ThresholdLoggingTracer, LoggingMeter, and spans output.

There are some different behaviors seen with this protocol:

* Some config options are unsupported -- see the xref:ref:client-settings.adoc#cloud-native-gateway[Settings page].
* The SDK will poll the gRPC channels until they are in a good state, or return an error, or timeout while waiting -- in our standard protocol there is an option of setting `waitUntilReady()` for just certain services to become available.
* Some error codes are more generic -- in cases where the client would not be expected to need to take specific action -- but should cause no problem, unless you have written code looking at individual strings within the error messages.
* Although documents continue to be stored compressed by Couchbase Server, they will not be transmitted in compressed form (to and from the client) over the wire, using `couchbase2://`.
// end::cng-limitations[]
































==============================




WaitUntilReady()

// tag::bootstrap-completion[]

[TIP]
.WaitUntilReady()
====
For some of the SDKs, such as xref:java-sdk:hello-world:start-using-sdk.adoc#opening-a-bucket[Java],
you'll see a recommendation to use `waitUntilReady()`,
which ensures that the bucket resource is fully loaded before proceeding.

Although this is an element of the https://github.com/couchbaselabs/sdk-rfcs/blob/master/rfc/0048-sdk3-bootstrapping.md[SDK bootstrapping RFC],
it's not required for successful operation of the "wrapper" SDKs (Node.js, PHP, Python, and Ruby -- wrappers over the {cpp} SDK),
as `Cluster.connect()` blocks until bootstrap is complete and a cluster config is seen. 
Any bootstrap errors are returned there.

// "There is still value in having wait_until_ready though, because it can be used to ensure all services are in a ready state (similar to ping).”
====
// end::bootstrap-completion[]



== Working in the Cloud

// tag::cloud[]
For most use cases, connecting client software using a Couchbase SDK to the xref:cloud:ROOT:index.adoc[Couchbase Capella service] is similar to connecting to an on-premises Couchbase Cluster.
The use of DNS-SRV, Alternate Address, and TLS is covered above.

We strongly recommend that the client and server xref:project-docs:compatibility.adoc#network-requirements[are in the same LAN-like environment] (e.g. AWS Region).
As this may not always be possible during development, read the guidance on working with xref:ref:client-settings.adoc#commonly-used-options[constrained network environments].
More details on connecting your client code to Couchbase Capella can be found xref:cloud:clouds:connect.adoc#connecting-from-sdk-cli-or-cbsh[in the Cloud docs].


=== Troubleshooting Connections to Cloud

Some DNS caching providers (notably, home routers) can’t handle an SRV record that’s large -- if you have DNS-SRV issues with such a set-up, reduce your DNS-SRV to only include three records.
[_For development only, not production._]. 
Our xref:troubleshooting-cloud-connections.adoc[Troubleshooting Cloud Connections] page will help you to diagnose this and other problems -- as well as introducing the SDK doctor tool.
// end::cloud[]

