WaitUntilReady()

// tag::bootstrap-completion[]

[TIP]
.WaitUntilReady()
====
For some of the SDKs, such as xref:java-sdk:hello-world:start-using-sdk.adoc#opening-a-bucket[Java],
you'll see a recommendation to use `waitUntilReady()`,
which ensures that the bucket resource is fully loaded before proceeding.

Although this is an element of the https://github.com/couchbaselabs/sdk-rfcs/blob/master/rfc/0048-sdk3-bootstrapping.md[SDK bootstrapping RFC],
it's not required for successful operation of the "wrapper" SDKs (Node.js, PHP, Python, and Ruby -- wrappers over the {cpp} SDK),
as `Cluster.connect()` blocks until bootstrap is complete and a cluster config is seen. 
Any bootstrap errors are returned there.

// "There is still value in having wait_until_ready though, because it can be used to ensure all services are in a ready state (similar to ping).”
====
// end::bootstrap-completion[]



== Working in the Cloud

// tag::cloud[]
For most use cases, connecting client software using a Couchbase SDK to the xref:cloud:ROOT:index.adoc[Couchbase Capella service] is similar to connecting to an on-premises Couchbase Cluster.
The use of DNS-SRV, Alternate Address, and TLS is covered above.

We strongly recommend that the client and server xref:project-docs:compatibility.adoc#network-requirements[are in the same LAN-like environment] (e.g. AWS Region).
As this may not always be possible during development, read the guidance on working with xref:ref:client-settings.adoc#commonly-used-options[constrained network environments].
More details on connecting your client code to Couchbase Capella can be found xref:cloud:clouds:connect.adoc#connecting-from-sdk-cli-or-cbsh[in the Cloud docs].


=== Troubleshooting Connections to Cloud

Some DNS caching providers (notably, home routers) can’t handle an SRV record that’s large -- if you have DNS-SRV issues with such a set-up, reduce your DNS-SRV to only include three records.
[_For development only, not production._]. 
Our xref:troubleshooting-cloud-connections.adoc[Troubleshooting Cloud Connections] page will help you to diagnose this and other problems -- as well as introducing the SDK doctor tool.
// end::cloud[]

