=== Network Requirements

Couchbase SDKs are developed to be run in an environment with local area network (LAN) like throughput and latencies.
While there is no technical issue that prevents the use across a wide area network (WAN), SDKs have certain thresholds around timeouts and behaviors to recover that will not be the same once the higher latency and possible bandwidth constraints and congestion of a WAN is introduced.
Couchbase tests for correctness under LAN like conditions.
For this reason, only LAN-like network environments are officially supported.

Couchbase does document, for purposes of convenience when developing and performing basic operational work, what may need to be tuned when network throughputs and latencies are higher.
If you encounter issues, even with these tune-ables, you should attempt the same workload from a supported, LAN-like environment.

==== Serverless Environments

Recent SDKs have better resilience in handling errors that may occur when running your application in serverless environments, in particular when processes are frozen or thawed, and a rebalance is required.
This means official support for AWS Lambda, Azure Functions, and GCP Functions.

NOTE: When *DNS SRV* records are used to connect to the SDK it is possible for the underlying addresses to change (i.e. the cluster could move).
The SDK will detect this and react accordingly so that your application can continue to work correctly.
