== Network Requirements

Couchbase SDKs are developed to be run in an environment with local area network (LAN) like throughput and latencies.
While there is no technical issue that prevents the use across a wide area network (WAN), SDKs have certain thresholds around timeouts and behaviors to recover that will not be the same once the higher latency and possible bandwidth constraints and congestion of a WAN is introduced.
Couchbase tests for correctness under LAN like conditions.
For this reason, only LAN-like network environments are officially supported.

Couchbase does document, for purposes of convenience when developing and performing basic operational work, what may need to be tuned when network throughputs and latencies are higher.
If you encounter issues, even with these tune-ables, you should attempt the same workload from a supported, LAN-like environment.

[IMPORTANT]
.Running on AWS Lambda
====
AWS Lambda’s execution environment can freeze processes, and when the client application running on the λ comes back up ("thaw"), unexpected behaviour may arise.
For this reason AWS λ is not a supported platform for running current Couchbase SDKs.
====
