= RBAC
:page-topic-type: concept
:page-aliases:


[abstract]
RBAC restrict resources on a Couchbase cluster to an identified user, allocated by role.




=== Roles and RBAC

// tag::security[]
Self-managed Couchbase Server uses Role-Based Access Control (RBAC), which is reflected in our managed service as a nuanced set of Roles.
Data security depends in part on only giving access to as much data as is needed to accomplish the task, and only as much ability to alter the data as is necessary.

RBAC restrict resources on a Couchbase cluster to an identified user, allocated by role.
// end::security[]



// tag::roles[]
==== Users, Resources, Roles, and Privileges

Couchbase Server Enterprise Edition uses _Role-Based Access Control_ for applications to restrict _resources_ on a Couchbase cluster to an identified _user_.

Each user who attempts resource-access is identified by means of the _credentials_ they pass to Couchbase Server, for purposes of _authentication_: these consist of a _username_ and (typically) a _password_.
Once the user is authenticated, an _authorization_ process checks the _roles_ with which the user is associated.
If one or more of these roles correspond to _privileges_ that permit the user-requested level of resource-access, access is duly granted; otherwise, it is denied.

Users who have been assigned the *Admin* role for the cluster are able to create, edit, and remove users.
The SDK provides APIs to support these activities.

NOTE: Introductory examples in the SDK documentation use the _Administrator_ user to ensure that developers can quickly get up and running; this _should not be used in production_.
Elsewhere we use a general "user" which represents whichever permission levels are appropriate to your application.
// end::roles[]


== Further Information

All aspects of the Couchbase RBAC system are covered in the section xref:7.1@server:learn:security/authorization-overview.adoc[Authorization].
Specifically, for information on:

* Adding _Users_ and assigning _roles_, by means of the Couchbase Web Console, see xref:7.1@server:manage:manage-security/manage-users-and-roles.adoc[Manage Users and Roles].
* _Roles_ required for resource-access, and the privileges they entail, see xref:7.1@server:learn:security/roles.adoc[Roles].
* _Resources_ controlled by Couchbase RBAC, see xref:7.1@server:learn:security/resources-under-access-control.adoc[Resources Under Access Control].

// tag::info[]
All aspects of the Couchbase RBAC system are covered in the section xref:{version-server}@server:learn:security/authorization-overview.adoc[Authorization].
Specifically, for information on:

* Adding _Users_ and assigning _roles_, by means of the Couchbase Web Console, see xref:{version-server}@server:manage:manage-security/manage-users-and-roles.adoc[Manage Users and Roles].
* _Roles_ required for resource-access, and the privileges they entail, see xref:{version-server}@server:learn:security/roles.adoc[Roles].
* _Resources_ controlled by Couchbase RBAC, see xref:{version-server}@server:learn:security/resources-under-access-control.adoc[Resources Under Access Control].
// end::info[]

