= SDK Release Notes
:description: Release notes, installation instructions, and download archive for the Couchbase {name_platform} Client.
:navtitle: Release Notes
:page-toclevels: 2
:page-partial:
// :page-aliases: relnotes-java-sdk.adoc,ROOT:sdk-release-notes.adoc,ROOT:relnotes-java-sdk.adoc,ROOT:release-notes.adoc,ROOT:download-links.adoc,server:sdks:java-2.2/download-links.adoc

[abstract]
{description}


// tag::intro[]
These pages cover the {sdk_dot_major} versions of the Couchbase {name_platform} SDK. 
For release notes, download links, and installation methods for {archive_version} and earlier releases of the Couchbase {name_platform} Client, please see the https://docs-archive.couchbase.com/{name_platform_lc}-sdk/{archive_version}/sdk-release-notes.html[{archive_major} {name_platform} Release Notes & Download Archive].

Version {sdk_dot_minor} of the {name_platform} SDK implements the {sdk_api} xref:compatibility.adoc#api-version[SDK API].
See the xref:compatibility.adoc#couchbase-feature-availability-matrix[compatibility pages] for more information on feature compatibility with different versions of Couchbase Server.
// end::intro[]



// tag::intro-no-archive[]
These pages cover the {sdk_dot_major} versions of the Couchbase {name_platform} SDK. 

Version {sdk_dot_minor} of the {name_platform} SDK implements the {sdk_api} xref:compatibility.adoc#api-version[SDK API].
See the xref:compatibility.adoc#couchbase-feature-availability-matrix[compatibility pages] for more information on feature compatibility with different versions of Couchbase Server.
// end::intro-no-archive[]



=== Installation

// tag::installation[]
See the xref:project-docs:sdk-full-installation.adoc[Full Installation] guide for details.
// end::installation[]

// tag::installation-moved[]
The full installation instructions that were previously on this page can now be found xref:project-docs:sdk-full-installation.adoc[here].
// end::installation-moved[]


=== API Documentation

The most current and up to date API Documentation is always available through the https://pkg.go.dev/github.com/couchbase/gocb/v2[godoc website].


// jvm signed
include::{version-common}@sdk:pages:partial$signed.adoc[tag=signed]

// tag::signed[]
=== Verifying Artifacts

Starting with version 3.8.2, Couchbase JVM SDK artifacts are signed with xref:java-sdk:project-docs:attachment$gpg-keys/181C7A4E908890A2D768365742BDEBD30D10C992.asc[this GPG key].

.Fingerprint
[source]
----
CB SDK Robot <cb-sdk-robot@couchbase.com>
181C 7A4E 9088 90A2 D768  3657 42BD EBD3 0D10 C992
----
// end::signed[]



== Older Releases

// tag::older[]
Although https://www.couchbase.com/support-policy/EOL/[no longer supported], documentation for older releases continues to be available in our https://docs-archive.couchbase.com/home/index.html[docs archive].
// end::older[]
