= Travel Sample Application

The aim of the Travel Sample Application, and this accompanying tutorial, is to introduce you to the basics of client code for Couchbase Serve, covering KeyValue and Sub-Document access, as well as Query (N1QL) and Full Text Search (FTS) services.









// tag::prereq[]
Travel Sample Application uses the Travel Sample data Bucket, which ships with Couchbase Server.
For Couchbase Server 6.5, make sure that you have at least one node each of data; query; index; and search.
For a development box, mixing more than one of these on a single node (given enough memory resources) is perfectly acceptable.
If you have yet to install Couchbase Server in your development environment, xref:6.5@server:getting-started:do-a-quick-install.adoc[start here].

Then load up the Travel Sample Bucket, using either the xref:6.5@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-ui[Web interface] 
or the xref:6.5@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-cli[command line].
You will also need to xref:6.5@server:fts:fts-searching-from-the-ui.adoc#create-an-index[create a Search Index] called `hotels`, for all documents of type `hotel`.
Query indexes are taken care of by the Sample Bucket.
// end::prereq[]


WARNING: This is a sample application, using sample data, running this on a production box would be unwise.







== Prerequisites



* Couchbase Server 6.5 or above, with _Data_ and _Search_ enabled.
Preferably running locally.
* A xref:hello-world:start-using-sdk.adoc[3.0 version of your SDK] -- _preferably_ the latest release.
* The travel sample app for your SDK












== See Also

* The Travel Sample's data model is briefly covered xref:ref:??????[in this reference page], for those wanting a more complete picture of what's going on in the application.

