// tag::abstract[]
[abstract]
{description}
This version demonstrates various features of Couchbase, including the Collections feature new in Server 7.0.
// end::abstract[]


// tag::quick-start[]
== Quick Start

Fetch the https://github.com/couchbaselabs/{travel-sample-git-project}[Couchbase {name-sdk} travel-sample Application REST Backend] from github:

[source,console,subs="+attributes"]
----
git clone https://github.com/couchbaselabs/{travel-sample-git-project}.git
cd {travel-sample-git-project}
----

With https://docs.docker.com/get-docker/[Docker] installed, you should now be able to run a bare-bones copy of Couchbase Server, load the travel-sample, add indexes, install the sample-application and its frontend, all by running a single command:

[source,console]
----
docker-compose up
----
// end::quick-start[]


// tag::bring-your-own[]
== Running the code against your own development Couchbase server.

// tag::prereq[]
For Couchbase Server {version-server}, make sure that you have at least one node each of data; query; index; and search.
For a development box, mixing more than one of these on a single node (given enough memory resources) is perfectly acceptable.

If you have yet to install Couchbase Server in your development environment
xref:{version-server}@server:getting-started:do-a-quick-install.adoc[start here].

Then load up the Travel Sample Bucket, using either the
xref:{version-server}@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-ui[Web interface]
or the
xref:{version-server}@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-cli[command line].
You will also need to
xref:{version-server}@server:fts:fts-searching-from-the-ui.adoc#create-an-index[create a Search Index]
-- Query indexes are taken care of by the Sample Bucket.
// end::prereq[]

See the README at https://github.com/couchbaselabs/{travel-sample-git-project} for full details of how to run and tweak the {name-sdk} travel-sample app.
// end::bring-your-own[]


// tag::using[]
== Using the Sample App

// TODO: *PIC -- screenshot

Give yourself a username and password and click *Register*.

Now try out a few queries, and see Search in action for the hotel finder feature.
// end::using[]


// tag::data-model[]
== Data Model

See the xref:ref:travel-app-data-model.adoc[Travel App Data Model] reference page for more information about the sample data set used.
// end::data-model[]


// tag::rest-api[]
== REST API

You can explore the REST API here in read-only mode, or once you are running the application, at the `/apidocs` endpoint.

swagger_ui::https://raw.githubusercontent.com/couchbaselabs/{travel-sample-git-project}/HEAD/swagger.json[]
// end::rest-api[]