= Extended Attributes

[abstract]
Couchbase Server permits the definition of _extended attributes_.
These allow application developers to define application-specific metadata that will only be visible to those applications that request it or attempt to modify it.
This might be, for example, meta-data specific to a programming framework that should be hidden by default from other frameworks, or possibly from other versions of the same framework.

[#using_extended_attributes]
// tag::using_extended_attributes[]
== Using Extended Attributes

The SDK supports extended attributes by means of extensions to the _Sub-Document API_: so that extended attributes can be defined, searched for, edited, removed, and more.
In order to specify that a subdocument operation should be performed on an extended rather than a regular attribute, an `xattr` flag should be set to `true`, by the calling application.

_Virtual_ extended attributes consist of metadata on an individual document: this can be retrieved by specifying `$document` as a search-path.

For more information, see xref:6.0@server:learn:data/extended-attributes-fundamentals.adoc[Extended Attributes].
// end::using_extended_attributes[]
