= Extended Attributes

[abstract]
Extended Attributes (XATTRs) are metadata that can be provided on a per-application basis.

// tag::intro_extended_attributes[]
Couchbase Server permits the addition of _extended attributes_ (XATTRs).

These allow developers to define application-specific metadata that will only be visible to those applications that request it or attempt to modify it.
This might be, for example, meta-data specific to a programming framework that should be hidden by default from other frameworks, or possibly from other versions of the same framework.
They are not intended for use in general applications, only libraries and frameworks, and data stored there cannot be accessed easily by some Couchbase services, such as Search.
// end::intro_extended_attributes[]

[#using_extended_attributes]
// tag::using_extended_attributes[]
== Using Extended Attributes

The SDK supports extended attributes by means of extensions to the _Sub-Document API_: so that extended attributes can be defined, searched for, edited, removed, and more.
In order to specify that a subdocument operation should be performed on an extended rather than a regular attribute, an `xattr` flag should be set to `true`, by the calling application.
For detailed information on the Subdocument API, see xref:subdocument-operations.adoc[Subdocument Operations], and the accompanying xref:howtos:subdocument-operations.adoc[practical doc].

For more information, see xref:6.5@server:learn:data/extended-attributes-fundamentals.adoc[Extended Attributes].
//, and our xref:howtos:sdk-xattr-example.adoc[example code].

NOTE: The maximum content size for a document stored in Couchbase Server is 20MB.
XATTRs -- including Virtual XATTRs -- will reduce the space available for the remainder of the document.

// end::using_extended_attributes[]


// tag::virtual_extended_attributes[]
== Virtual Extended Attributes

_Virtual_ extended attributes consist of metadata on an individual document: this can be retrieved by specifying `$document` as a search-path -- see below.
See xref:6.5@server:learn:data/extended-attributes-fundamentals.adoc#virtual-extended-attributes[the Virtual XATTR Section] for more information on the metadata that they expose.

These attributes are generated on-demand to expose storage-level document metadata, such as expiry to expose document expiration.
For expiry using Virtual XATTR, use the following:
// end::virtual_extended_attributes[]

// Section below goes in each Sub-Doc HOWTO

// tag::extended_attributes[]
== Extended Attributes

Extended Attributes (also known as XATTRs), built upon the Sub-Document API, allow developers to define application-specific metadata that will only be visible to those applications that request it or attempt to modify it.
This might be, for example, meta-data specific to a programming framework that should be hidden by default from other frameworks or libraries, or possibly from other versions of the same framework.
They are not intended for use in general applications, and data stored there cannot be accessed easily by some Couchbase services, such as Search.
// end::extended_attributes[]
