= Threshold Logging Tracing

[abstract]
By collecting and analyzing each operation an SDK performs, information can be made available to identify problem areas when an operation takes an unusually long time to complete.
For example pin-pointing whether any delay lies with network issues, rather than a Couchbase Server operation, or if most delays are concentrated on a particular Server node.
(Response Time Observability, a.k.a.
Tracing, is Enterprise Edition only - not available in the Community Edition.)

IMPORTANT: Threshold Logging Tracing is part of the SDK, and will work with both the Community and Enterprise Editions of Couchbase Server.
However, Data Service operation duration is only available in the Enterprise Edition.

[#why_tracing]
// tag::why_tracing[]
== Why Tracing?

Tracing is recording details about discrete steps or phases of a request lifecycle, such as request encoding / decoding, or dispatching to server.
These phases are timed independently, and contain additional contextual information.
A single request is typically made up of multiple tracing points.
// end::why_tracing[]

[#open_tracing]
// tag::open_tracing[]
== Open Tracing

http://opentracing.io/[OpenTracing^] is a standardised API to structure tracing information in a consistent and predictable manner.
// end::open_tracing[]

[#threshold_configuration]
// tag::threshold_configuration[]
== Threshold Configuration Settings

The threshold tracer receives completed spans and verifies if an operation has exceeded the given threshold for the operation type.
Operations that exceed the threshold are periodically logged with a total count and a sample of the slowest ones.
The following are SDK configuration properties.

.Threshold Logging Tracer Properties
[#threshold-logging-tracer-ref,cols="3,3,1"]
|===
| Property Name | Description | Default Value

| `OperationTracingEnabled`
| Boolean used to determine tracing is enabled.
Defaults to using the `ThesholdLoggingTracer` if enabled.
When false a Noop or similar tracing implementation should be used instead.
| true

| `OperationTracingServerDurationEnabled`
| Boolean used to instruct the SDK to try and retrieve duration metrics from the server for KV operations.
| true

| `ThresholdLoggingTracerInterval`
| The interval between executions that process the collected operation spans.
Expressed in milliseconds.
| 10,000 (10 seconds)

| `ThresholdLoggingTracerSampleSize`
| The maximum number of items to log per service.
| 10

| `ThresholdLoggingTracerKVThreshold`
| The KV operation operation threshold.
Expressed in microseconds.
| 500,000 (500 milliseconds)

| `ThresholdLoggingTracerViewsThreshold`
| The View query operation threshold.
Expressed in microseconds.
| 1,000,000 (1 second)

| `ThresholdLoggingTracerQueryThreshold`
| The N1QL query operation threshold.
Expressed in microseconds.
| 1,000,000 (1 second)

| `ThresholdLoggingTracerSearchThreshold`
| The FTS query operation threshold.
Expressed in microseconds.
| 1,000,000 (1 second)

| `ThresholdLoggingTracerAnalyticsThreshold`
| The Analytics query operation threshold.
Expressed in microseconds.
| 1,000,000 (1 second)

| `OrphanedResponseLoggingEnabled`
| Boolean used to determine if orphaned response logging is enabled.
| true

| `OrphanedResponseLoggingInterval`
| The interval used to flush orphaned response information to the log.
Expressed in microseconds.
| 10,000 (10 seconds)

| `OrphanedResponseLoggingSampleSize`
| The number of sample orphaned responses whose to log additional information for per execution.
| 10
|===
// end::threshold_configuration[]
