
= MapReduce Views

[abstract]
You can use MapReduce views to create queryable indexes in Couchbase Server.

// tag::views-intro[]
The normal CRUD methods allow you to look up a document by its ID.
A MapReduce (_view_ query) allows you to lookup one or more documents based on various criteria.
MapReduce views are comprised of a _map_ function that is executed once per document (this is done incrementally, so this is not run each time you query the view) and an optional _reduce_ function that performs aggregation on the results of the _map_ function.
The _map_ and _reduce_ functions are stored on the server and written in JavaScript.

MapReduce queries can be further customized during query time to allow only a subset (or range) of the data to be returned.

TIP: See the xref:7.1@server:learn:views/views-writing.adoc[Incremental MapReduce Views] and xref:7.1@server:learn:views/views-querying.adoc[Querying Data with Views] sections of the general documentation to learn more about views and their architecture.
// end::views-intro[]

// tag::example-beer[]

== By Name Views

The following example is the definition of a `by_name` view in a _"beer"_ design document.
This view checks whether a document is a beer and has a name.
If it does, it emits the beer's name into the index.
This view allows beers to be queried for by name.
For example, it's now possible to ask the question "What beers start with A?"
// end::example-beer[]

// tag::example-travel[]
The following example is the definition of a `by_name` view in a _"landmarks"_ design document in the _"travel-sample"_ sample dataset.
This view checks whether a document is a landmark and has a name.
If it does, it emits the landmark's name into the index.
This view allows landmarks to be queried for by its _"name"_ field.
// end::example-travel[]

// tag::example-geo-travel[]
A Spatial View can instead be queried with a [.param]`range` or _bounding box_.
For example, let's imagine we have stored landmarks with coordinates for their home city (eg.
Paris, Vienna, Berlin and New York) under [.param]`geo`, and each city's coordinates is represented as two attributes, [.param]`lon` and [.param]`lat`.
The following spatial view map function could be used to find landmarks within Europe, as a _"by_location"_ view in a _"spatial"_ design document:
// end::example-geo-travel[]

// tag::deprecate[]
[CAUTION]
====
Although still maintained and supported for legacy use, Views date from the earliest days of Couchbase Server development, and as such are rarely the best choice over, say, xref:howtos:n1ql-queries-with-sdk.adoc[our Query service] if you are starting a fresh application.
See our discussion document on xref:concept-docs:data-services.adoc[the best service for you to use].

Note, if you are provisioning Views on Couchbase Server for a legacy application, _they must run on a 
xref:7.2@server:learn:buckets-memory-and-storage/storage-engines.adoc#couchstore[couchstore] bucket_.
====
// end::deprecate[]

// tag::deprecate2[]
CAUTION: Views is deprecated in Couchbase Server 7.0, and will eventually move to unsupported status.
Use our xref:howtos:n1ql-queries-with-sdk.adoc[Query Service] if you are starting a fresh application, or see our discussion document on xref:concept-docs:data-services.adoc[the best service for you to use].
We will maintain support for Views in the SDKs for so long as it can be used with a supported version of Couchbase Server.
// end::deprecate2[]
