= MapReduce Views

[abstract]
You can use MapReduce views to create queryable indexes in Couchbase Server.

[#views-intro]
// tag::views-intro[]
--
The normal CRUD methods allow you to look up a document by its ID.
A MapReduce (_view_ query) allows you to look up one or more documents based on various criteria.
MapReduce views are comprised of a _map_ function that is executed once per document (this is done incrementally, so this is not run each time you query the view) and an optional _reduce_ function that performs aggregation on the results of the _map_ function.
The _map_ and _reduce_ functions are stored on the server and written in JavaScript.

MapReduce queries can be further customized during query time to allow only a subset (or range) of the data to be returned.

TIP: See xref:6.0@server:understanding-couchbase:views/views-intro.adoc[Views].
--
// end::views-intro[]

[#example-beer]
// tag::example-beer[]
--
The following example is the definition of a `by_name` view in a _"beer"_ design document.
This view checks whether a document is a beer and has a name.
If it does, it emits the beer's name into the index.
This view allows beers to be queried for by name.
For example, it's now possible to ask the question "What beers start with A?"

[source,javascript]
----
function (doc, meta) {
    if (doc.type && doc.type == "beer" && doc.name) {
        emit(doc.name, null);
    }
}
----
--
// end::example-beer[]

[#example-travel]
// tag::example-travel[]
--
The following example is the definition of a `by_name` view in a _"landmarks"_ design document in the _"travel-sample"_ sample dataset.
This view checks whether a document is a landmark and has a name.
If it does, it emits the landmark's name into the index.
This view allows landmarks to be queried for by it's _"name"_ field.

[source,javascript]
----
function (doc, meta) {
    if (doc.type && doc.type == "landmark" && doc.name) {
        emit(doc.name, null);
    }
}
----
--
// end::example-travel[]

[#example-geo-travel]
// tag::example-geo-travel[]
--
A Spatial View can instead be queried with a [.param]`range` or _bounding box_.
For example, let's imagine we have stored landmarks with coordinates for their home city (eg.
Paris, Vienna, Berlin and New York) under [.param]`geo`, and each city's coordinates is represented as two attributes, [.param]`lon` and [.param]`lat`.
The following spatial view map function could be used to find landmarks within Europe, as a _"by_location"_ view in a _"spatial"_ design document:

[source,javascript]
----
function (doc, meta) {
    if (doc.type && doc.type == "landmark" && doc.geo) {
        emit([doc.geo.lon, doc.geo.lat], null);
    }
}
----
--
// end::example-geo-travel[]
