= Glossary of SDK-related Terms
:navtitle: Glossary
:page-topic-type: project-doc
:page-aliases: 

[abstract] Unpicking the tangled alphabet soup of the Couchbase Platform, from an SDK perspective.

The Couchbase Data platform offers several services, and many advanced features, which we document here, in the Couchbase SDK documentation.
Below you will find short definitions of many Couchbase-related terms, with links to the pages that describe them in more detail, or show practical examples of their use.

// Forms a sort of index of links

* xref:howtos:analytics-using-sdk.adoc[Analytics] -- Couchbase Analytics Service allows longer running queries over big data, whilst taking advantage of Couchbase’s Multi-Dimensional scaling.
// Bootstrapping -
* xref:howtos:concurrent-document-mutations.adoc[CAS] -- Check And Swap. 
A value which is altered each time a document is mutated. 
Used in Concurrent Document Mutations for a type of optimistic logging.
* xref:howtos:sdk-authentication.adoc#certificate-authentication[Cert Auth] -- Certificate Authentication (xref:6.6@server:introduction:editions.adoc[Enterprise Edition] only). 
A client attempting to access Couchbase Server can present a certificate to the server, allowing the server to check the validity of the certificate. 
If the certificate is valid, the user under whose identity the client is running, and the roles assigned that user, are verified. If the assigned roles are appropriate for the level of access requested to the specified resource, access is granted.
* xref:howtos:provisioning-cluster-resources.adoc[Cluster Provisioning] -- The primary means for managing clusters is through the Couchbase Web UI which provides an easy to use interface for adding, removing, monitoring and modifying buckets. 
In some instances you may wish to have a programmatic interface. For example, if you wish to manage a cluster from a setup script, or if you are setting up buckets in test scaffolding.
The SDK also comes with some convenience functionality for common Couchbase management requests, particularly in the 3.0 SDK API.
* xref:concept-docs:collections.adoc[Collections] -- from Server 7.0 (and available as a xref:6.6@server:developer-preview:collections/collections-overview.adoc[Developer Preview] in Couchbase Server 6.5 and 6.6), _Collections_ allow groupings of documents beneath the Bucket level.
Bucket items can optionally be assigned to different collections according to content type.
* xref:howtos:transcoders-nonjson.adoc[Custom Transcoders] -- Whenever key-value data is sent to or retrieved from Couchbase Server, the SDK passes the data being sent to a transcoder. 
The transcoder can either reject the data as being unsupported, or convert it into a []byte and a Common Flag. 
Many applications will not need to be aware of transcoders, as the defaults support most standard JSON use cases. 
More advanced transcoding needs can be accomplished if the application implements their own transcoders and serializers.
* xref:6.6@server:learn:clusters-and-availability/intra-cluster-replication.adoc#database-change-protocol[DCP] -- 
Database Change Protocol (DCP) is the protocol used to stream bucket-level mutations. 
DCP is used for high-speed replication of mutations; to maintain replica vBuckets, incremental MapReduce and spatial views, Global Secondary Indexes (GSIs), XDCR, backups, and external connections.
This feed is not directly available, and users should look at xref:concept-docs:data-services.adoc#lowest-latency[other low latency alternatives].
Durability - 
(for older server versions, see xxx)

Encryption - see Field Level Encryption
Eventing -


Field Level Encryption (FLE) - 

FTS - Full Text Search

GC - Garbage Collection?

GSI -
   MOI,  non-MOI (?)

Index
...inc ?

xref:[KV Operations] - Key Value Operations work directly on the document, for CRUD operations on documents whose identity is known.

MapReduce Views

xref:[N1QL] - Couchbase’s powerful SQL-like language allows queries in a format familiar to Database Administrators.

xref:[Query] - The Couchbase Query Service uses a SQL-like language for powerful queries across documents.

RBAC

RTO - see Tracing
* xref:concept-docs:collections.adoc[Scopes] -- from Server 7.0 (and available as a xref:6.6@server:developer-preview:collections/collections-overview.adoc[Developer Preview] in Couchbase Server 6.5 and 6.6), _Collections_ allow groupings of documents beneath the Bucket level, and _Scopes_ group together Collections.
Collections might be assigned to different scopes according to content-type, or to deployment-phase (e.g., test and production). 
Applications can be assigned per-scope access rights, allowing each application to access only those collections it requires.



Scope - 

Sub-Doc - Sub-Document

Synchronous Replication - 

Sync-Gateway (? for awareness, also another possible source of interactions via mobile devices?)

Threshold Logging - see Tracing

Tracing - vs Response Time Observability vs Threshold Logging

Transactions

* Transcoders -- See _Custom Transcoders_, above.
Transcoders - see Custom Transcoders

Virtual XATTR

XATTR



// Link to Tony’s Server Glossary
// https://docs.couchbase.com/server/6.0/learn/glossary.html

== Further Reading

Glossaries are available for:

* xref:server:learn:glossary.adoc[Couchbase Server]
* xref:server:eventing:eventing-Terminologies.adoc[Couchbase Eventing Service]
* xref:couchbase-lite:android:refer/java-android-refer-glossary.adoc[Couchbase Lite (Android)]
* xref:sync-gateway:refer:refer-sgw-glossary.adoc[Sync Gateway]

Only the Server Glossary takes the form of an index, linking to other pages, in the same manner as this page.
