= Glossary
:page-aliases:
:page-topic-type: reference

[abstract]
Unpicking the tangled alphabet soup of the Couchbase Platform, from an SDK perspective.

The Couchbase Data platform offers several services, and many advanced features, which we document here, in the Couchbase SDK documentation.
Below you will find short definitions of many Couchbase-related terms, with links to the pages that describe them in more detail, or show practical examples of their use.

// Forms a sort of index of links

* xref:howtos:analytics-using-sdk.adoc[Analytics] -- Couchbase Analytics Service allows longer running queries over big data, whilst taking advantage of Couchbase’s Multi-Dimensional scaling.

// Columnar -- Real-time analytics
// Bootstrapping -
* xref:howtos:concurrent-document-mutations.adoc[CAS] -- Conpare And Swap.
A value which is altered each time a document is mutated.
Used in Concurrent Document Mutations for a type of optimistic logging.
* xref:howtos:sdk-authentication.adoc#certificate-authentication[Cert Auth] -- Certificate Authentication (Capella and xref:{server_version}@server:introduction:editions.adoc[Enterprise Edition] only).
A client attempting to access Couchbase Server can present a certificate to the server, allowing the server to check the validity of the certificate.
If the certificate is valid, the user under whose identity the client is running, and the roles assigned that user, are verified. If the assigned roles are appropriate for the level of access requested to the specified resource, access is granted.
* xref:howtos:provisioning-cluster-resources.adoc[Cluster Provisioning] -- The primary means for managing clusters is through the Couchbase Web UI which provides an easy to use interface for adding, removing, monitoring and modifying buckets.
In some instances you may wish to have a programmatic interface. For example, if you wish to manage a cluster from a setup script, or if you are setting up buckets in test scaffolding.
The SDK also comes with some convenience functionality for common Couchbase management requests.
* xref:concept-docs:collections.adoc[Collections] -- from Server 7.0, _Collections_ allow groupings of documents beneath the Bucket level.
Bucket items can optionally be assigned to different collections according to content type.
* xref:howtos:transcoders-nonjson.adoc[Custom Transcoders] -- Whenever key-value data is sent to or retrieved from Couchbase Server, the SDK passes the data being sent to a transcoder.
The transcoder can either reject the data as being unsupported, or convert it into a byte array and a Common Flag.
Many applications will not need to be aware of transcoders, as the defaults support most standard JSON use cases.
More advanced transcoding needs can be accomplished if the application implements their own transcoders and serializers.
* xref:{server_version}@server:learn:clusters-and-availability/intra-cluster-replication.adoc#database-change-protocol[DCP] --
Database Change Protocol (DCP) is the protocol used to stream bucket-level mutations.
DCP is used for high-speed replication of mutations; to maintain replica vBuckets, incremental MapReduce and spatial views, Global Secondary Indexes (GSIs), XDCR, backups, and external connections.
This feed is not directly available, and users should look at xref:concept-docs:data-services.adoc#lowest-latency[other low latency alternatives].
* xref:concept-docs:durability-replication-failure-considerations.adoc[Durability] -- Couchbase Server 6.0 and earlier, with 2.x API versions of the SDK, used Observe style durability; this is still available in most versions of SDK 3.x for working with earlier Server releases.
.all current, supported versions of Couchbase Server offer Server-side xref:{server_version}@server:learn:data/durability.adoc[Durable Writes].
See also _Transactions_, below.
* Encryption -- see _Field Level Encryption_, below.
* Extended Attributes -- see _XATTRs_, below.
* xref:{server_version}@server:learn:services-and-indexes/services/eventing-service.adoc[Eventing] -- The Eventing Service allows functions to be written, saved, and triggered in response to events.
Events include changes made to specified items, and the arrival of scheduled points-in-time.
There is limited interaction with the Eventing Service from the SDK.
* xref:concept-docs:encryption.adoc[Field Level Encryption (FLE)] -- encryption of the field or _value_ in a key-value pair, using a FIPS-140-2 compliant cryptography algorithm.
* xref:howtos:full-text-searching-with-sdk.adoc[Full Text Search (FTS)] --
Create, manage, and query full-text indexes on JSON documents stored in Couchbase buckets.
FTS uses natural language processing for indexing and querying documents, provides relevance scoring on the results of your queries, and has fast indexes for querying a wide range of possible text searches.
Some of the supported query-types include simple queries like Match and Term queries; range queries like Date Range and Numeric Range; and compound queries for conjunctions, disjunctions, and/or boolean queries.
Also integrates with Vector Search indexes.
* xref:{server_version}@server:learn:services-and-indexes/indexes/global-secondary-indexes.adoc[Global Secondary Indexes (GSI)] --
A Global Secondary Index (GSI) supports queries made by the Query Service on attributes within documents.
Secondary indexes -- which contain a filtered or a full set of keys in a given bucket -- are optional, but increase query efficiency on a bucket.
GSIs can be created xref:concept-docs:n1ql-query.adoc#indexes[through the SDK], using the {sqlpp} (formerly N1QL) `CREATE INDEX` statement.
See also xref:{server_version}@server:learn:services-and-indexes/indexes/storage-modes.adoc#memory-optimized-index-storage[Memory-Optimized Index Storage] (MOI).
* JSON & non-JSON -- Couchbase Services work with JSON documents (see https://tools.ietf.org/html/rfc8259[rfc8259^]),
but non-JSON storage is supported,  including UTF-8 strings, raw sequences of bytes, and language specific serializations --   see the xref:concept-docs:nonjson.adoc[Binary Storage Documentation].
Non-JSON formats may be more efficient in terms of memory and processing power (for example, if storing only flat strings, JSON adds an additional syntactical overhead of two bytes per string).
Non-JSON documents may be desirable if migrating a legacy application, which is using a xref:howtos:transcoders-nonjson.adoc[customized binary format].
JSON’s key-value structure allows the storage of collection data structures such as lists, maps, sets and queues -- see the xref:concept-docs:data-model.adoc[Data Model page];
JSON’s tree-like structure allows operations against xref:howtos:subdocument-operations.adoc[specific paths in the Document],
and efficient support for these data structures.
* xref:howtos:kv-operations.adoc[Key-Value Operations] -- KV Operations work directly on the document, for CRUD operations on documents whose identity (key) is known.
The Data (KV) Service uses a fast binary protocol, and is often the best choice for optimum performance.
* xref:howtos:view-queries-with-sdk.adoc[MapReduce Views] --
MapReduce Views uses distributed Map-Reduce for very fast aggregation operations (fast, because the indexes are pre-computed results) — ideal for pre-grouped aggregations, such as grouping temporal data sets (by day, by month, etc.).
However, Views are deprecated in the latest versions of Couchbase Server, and will eventually be removed.
Continuing improvements to our Query Service makes the latter usually a better choice, particularly as Views does not scale as well as the other services, lacking a global Index node.
* N1QL -- see _{sqlpp}_, below.
// Observability
* xref:howtos:n1ql-queries-with-sdk.adoc[Query] -- The Couchbase Query Service uses a SQL-like language for powerful queries across documents.
* xref:{server_version}@server:learn:security/authorization-overview.adoc#introduction-to-rbac[RBAC] -- Role-Based Access Control allows secure, fine-grained access privileges, assigned to fixed roles.
The 3.x API allows some user management programmatically from the SDK.
// RTO - see Tracing
* xref:concept-docs:collections.adoc[Scope] -- from Server 7.0, _Collections_ allow groupings of documents beneath the Bucket level, and _Scopes_ group together Collections.
Collections might be assigned to different scopes according to content-type, or to deployment-phase (e.g., test and production).
Applications can be assigned per-scope access rights, allowing each application to access only those collections it requires.
* xref:concept-docs:n1ql-query.adoc[{sqlpp}] -- Couchbase’s powerful SQL-like language (formerly N1QL) allows queries in a format familiar to Database Administrators.
These can be made against our Query Service, for transaction (OLTP) queries,
or against our analytics (OLAP) services -- CBAS or, for _real-time_ analytics, Capella Columnar.
* xref:howtos:subdocument-operations.adoc[Sub-Document Operations] --
Sub-Document retrievals only retrieve relevant parts of a document and Sub-Document updates only require sending the updated portions of a document.
Sub-Document operations are also atomic, in that if one Sub-Document mutation fails then all will, allowing safe modifications to documents with built-in concurrency control.
// Sync-Gateway (? for awareness, also another possible source of interactions via mobile devices?)
// Threshold Logging - see Tracing
// Tracing - vs Response Time Observability vs Threshold Logging
* xref:{server_version}@server:learn:data/transactions.adoc[Transactions] --
Distributed ACID Transactions guarantee that multiple documents can be updated atomically.
* Transcoders -- See _Custom Transcoders_, above.
* xref:howtos:vector-searching-with-sdk.adoc[Vector Search] -- With Couchbase Vector Search, you can enable fast and highly accurate semantic search, ground LLM responses in relevant data to reduce hallucinations, and enhance or enable use cases like personalized searches in e-commerce and media & entertainment, product recommendations, fraud detection, and reverse image search.
* xref:concept-docs:xattr.adoc#virtual-extended-attributes[Virtual XATTRs] --
Virtual Extended Attributes (VXATTR) consist of metadata on an individual document, generated on-demand to expose storage-level document metadata, such as `expiry` to expose document expiration.
* xref:howtos:subdocument-operations.adoc#extended-attributes[XATTRs] --
Extended Attributes (XATTRs), built upon the Sub-Document API, allow developers to define application-specific metadata that will only be visible to those applications that request it or attempt to modify it.
This might be, for example, meta-data specific to a programming framework that should be hidden by default from other frameworks or libraries, or possibly from other versions of the same framework.
They are not intended for use in general applications, and data stored there cannot be accessed easily by some Couchbase services, such as Search.


== Further Reading

Glossaries are available for:

* xref:server:learn:glossary.adoc[Couchbase Server]
* xref:server:eventing:eventing-Terminologies.adoc[Couchbase Eventing Service]
* xref:couchbase-lite:android:refer/java-android-refer-glossary.adoc[Couchbase Lite (Android)]
* xref:sync-gateway:ROOT:refer/refer-sgw-glossary.adoc[Sync Gateway]

Only the Server Glossary takes the form of an index, linking to other pages, in the same manner as this page.
