= Health Check
:nav-title: Health Check
:page-topic-type: concept
:page-aliases: ROOT:health-check

[abstract]
Health Check provides ping() and diagnostics() tests for the health of the network and the cluster.

Working in distributed environments is _hard_.
Latencies come and go, so do connections in their entirity.
Is it a network glitch, or is the remote cluster down?
Sometimes just knowing the likely cause is enough to get a good start on a workaround, or at least avoid hours wasted on an inappropriate solution.

Health Check enables useful diagnostics on the state of Couchbase Clusters across networks. 
`Ping` and `diagnostics` methods on the bucket and cluster objects respectively, can give us information about the current state of nodes, and their connections.

== Uses

'Ping` provides a raw JSON payload suitable for feeding into reactive log and aggregation components, including monitoring systems like _Splunk_, _ElasticSearch_, and _Nagios_.
It can also help keep connections alive if you are operating across an environment which aggressively closes down unused connections.

`Diagnostics` provides a strongly typed API for proactive, pull-based monitoring systems, such as:

* https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/[Kubernetes Liveness and Readiness Probes via HTTP or CLI commands].
* https://docs.docker.com/engine/reference/builder/#healthcheck[Docker Health Check with CLI commands].
* http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-healthchecks.html[AWS ELB through HTTP].

This API does not provide binary yes/no answers about the health of the cluster; rather it summarizes as much information as possible, for the application developer to assemble a complete, contextual view and come to a conclusion.

Note: `Ping` may reopen a connection, so is not without side-effects.
`Diagnostics` shows what the SDK _perceives_ as the current state of the network and services -- it is without side-effects, but may not be up to date.


== Ping

`Ping` _actively_ queries the status of the specified services,giving status and latency information for every node reachable.
In addition to its use as a monitoring tool, a regular `Ping` can be used in an environment which does not respect keep alive values for a connection. 
This is a Map (a JavaScript `object`) with `type` keys for each service available, such as `kv` and `n1ql`, and the value containing latency and status information.


[source,javascript]
----
let services = [couchbase.ServiceType.KeyValue, couchbase.ServiceType.Query]
bucket.ping(services, (err, res) => {
    console.log(res)
})
/*
{
    "config_rev":1822,
    "id":"0x102f09dc0",
    "sdk":"libcouchbase/2.9.5-njs couchnode/2.6.9 (node/10.16.0; v8/6.8.275.32-node.52; ssl/1.1.1b)",
    "services":{
        "kv":[
            {
                "id":"0x104802900",
                "latency_us":1542,
                "local":"10.112.195.1:51707",
                "remote":"10.112.195.101:11210",
                "scope":"travel-sample",
                "status":"ok"
            },
            {
                "id":"0x1029253d0",
                "latency_us":6639,
                "local":"10.112.195.1:51714",
                "remote":"10.112.195.103:11210",
                "scope":"travel-sample",
                "status":"ok"
            },
            {
                "id":"0x102924bc0",
                "latency_us":1240660,
                "local":"10.112.195.1:51713",
                "remote":"10.112.195.102:11210",
                "scope":"travel-sample",
                "status":"timeout"
            }
        ],
        "n1ql":[
            {
                "id":"0x10291d980",
                "latency_us":3787,
                "local":"10.112.195.1:51710",
                "remote":"10.112.195.101:8093",
                "status":"ok"
            },
            {
                "id":"0x1029240f0",
                "latency_us":9321,
                "local":"10.112.195.1:51712",
                "remote":"10.112.195.103:8093",
                "status":"ok"
            },
            {
                "id":"0x102923350",
                "latency_us":7003363,
                "local":"10.112.195.1:51711",
                "remote":"10.112.195.102:8093",
                "status":"timeout"
            }
        ]
    },
    "version":1
}
*/
----


== Diagnostics

`Diagnostics` returns a list of the nodes that the SDK currently has (or had) a connection to, and the current status of the connection.
However this call _does not_ actively poll the nodes, reporting instead the state the last time it tried to access each node.
If you want the _current_ status, then use xref:#ping[Ping].

[source,javascript]
----
bucket.diagnostics((err, res) => {
    console.log(res)
})
/*
{
    "id":"0x10290d100","kv":[
        {
            "id":"0000000072b21d66",
            "last_activity_us":2363294,
            "local":"10.112.195.1:51473",
            "remote":"10.112.195.101:11210",
            "status":"connected"
        },
        {
            "id":"000000000ba84e5e",
            "last_activity_us":7369021,
            "local":"10.112.195.1:51486",
            "remote":"10.112.195.102:11210",
            "status":"connected"
        },
        {
            "id":"0000000077689398",
            "last_activity_us":4855640,
            "local":"10.112.195.1:51409",
            "remote":"10.112.195.103:11210",
            "status":"connected"
        }
    ],
    "sdk":"libcouchbase/2.9.5-njs couchnode/2.6.9 (node/10.16.0; v8/6.8.275.32-node.52; ssl/1.1.1b)",
    "version":1
}
*/
----

// above needs updating and localising (per SDK) for 3.0




////

== Results Fields

// This section for ref Doc?
// (after MD --> asciidoc translation)

The following sections describe the individual fields which are part of the JSON
payload as well as the `DiagnosticsResult` part of the actual API. Later
sections introduce both the raw JSON as well as the API.

## Version
- Mandatory, Integer

The report layout version. Currently it must always be `1`.

## ID
- Mandatory, String

The report must have `"id"` property, which might be configurable by SDK users,
and automatically generated otherwise (It should be at least unique in scope of
the application, but UUID is also fit). This field is able to be specified by
the user in the function call.

## Configuration revision
- Mandatory for `ping()`, Not used for `diagnostics()`, Integer

The `ping()` report should contain Reportrevision of the configuration that the
SDK is actively using when the report is generated. It also helps to determine
the full list of nodes.

## SDK identifier
- Mandatory, String

The same as identifier seen in HELO command and User-Agent in HTTP requests.

## Services
- Mandatory, Array

On the top level we have `"services"` key, which contains map of service keys, to
arrays of the endpoints.

| Service Key | Description                                                                                                                              |
|-------------|------------------------------------------------------------------------------------------------------------------------------------------|
| `"kv"`      | Memcached binary protocol sockets                                                                                                        |
| `"config"`  | If configuration colling mechanism uses dedicated sockets, they should use separate key (even though they technically `"kv"` or `"http"` |
| `"mgmt"`    | Sockets for management requests (administering the cluster or bucket properties                                                          |
| `"view"`    | Couchbase View queries                                                                                                                   |
| `"n1ql"`    | N1QL queries                                                                                                                             |
| `"fts"`     | Full text search (CBFT) queries                                                                                                          |
| `"cbas"`    | Analytics queries                                                                                                                        |

### Sevice Id
- Mandatory, String

The service object must have some string identifier (`"id"`), which is unique in
scope of resource container (the entity which generates report). For example, it
could be a socket descriptor, or corresponding in-memory address of wrapping
structure.

The Service id is a logical identifier for the same "socket structure", and
should stay the same across reconnect attempts for example (even if the
`"local"` field would change on a reconnect attempt).

When SDK does not control the socket directly, but still willing to expose
connection metrics, it could use the connection hashcode or object id here, so
that the user will be able to track connection throughout the several consequent
reports (in scope of report ID).

### Service state
- Mandatory, String

The list of service states provided here defines an exhaustive list, and it is
expected that not all SDKs are able to show all of these states, BUT they should
not define new states that are not part of this list. If additional information
is required, it can be placed in the "details" field.

The `"state"` field describes the current connection conditions. Here are all the
possible fields for the Diagnostics API:

* `"new"`: the connection is initialized but it has never been connected (or
  trying to) yet
* `"connecting"`: identifies the connection in the initial connect attempt
* `"authenticating"`: state during connecting or reconnecting where the client
  is actively performing the authentication (i.e. SASL).
* `"connected"`, normal case, everything operating
* `"disconnected"`, always indicated unexpectedly
* `"reconnecting"`: trying to reconnect after a first initial connect attempt
* `"disconnecting"`, planned, if say the map changed or the cluster requested a
  graceful connection shut down; some requests may still be in flight.

In case of PING API, the states defined as following:

* `"timeout"`: the server wasn't able to reply to ping request in time. The time
  should be the same as for corresponding service request.
* `"ok"`: the service responded with successful code, see `"latency_us"` for
  latency
* `"error"`: some error happened (more information might be supplied in
  `"details"`)

### Scope
- Mandatory for scoped services, String

On services which are scoped to a bucket, then the `"scope"` field needs to
reflect the bucket name. On services where there is no bucket scoping, the field
can be omitted (in practice, right now the scope field is needed for kv services
where the value is the bucket name).

### Service Latency
- Mandatory for `ping()` report, Integer

This field must specify latency time in microseconds. It has to be specified
when active keep-alive used (`ping()` API). Ignored for `diagnostics()` API.

### Service Last Activity
- Mandatory for `diagnostics()` report, Integer

The field must specify the time in microseconds since relative last activity of
the service (not absolute as in epoch). This field is mandatory, if activity
happened yet and can be omitted if none has happened yet (since 0 would be
ambiguous as there might have been traffic at the time of the health
check). Optional for ping report.

### Service Local Address
- Optional, String

This field must contain endpoint local address in `"host:port"` form. This field
is optional as not all HTTP libraries expose socket API.

### Service Remote Address
- Mandatory, String

This field must contain remote address that matches what was supplied in the
configuration from the cluster and not be modified in the SDK (like resolve it),
which `$HOST` substitution if necessary. This field is mandatory.

### Service Details
- Optional, String

The endpoint entry of the JSON might contain optional field `"details"` with the
string, describing current state of the endpoint. It might be a humanized
description of the current state (status code for example, next time to
reconnect etc.). Those details can also contain SDK specific information and are
not standardized as part of this RFC.



////


