= Licenses
:description: Couchbase SDKs' source code and binaries are licensed under the Apache Licence 2.0.
:page-aliases: ROOT:sdk-licenses.adoc

[abstract]
{description}
Dependencies carry their own licenses.


Source and any and all binaries for the Couchbase {name_platform} Client are distributed under the https://www.apache.org/licenses/LICENSE-2.0[Apache License, Version 2.0].


== Support Level

Support level will match the terms of your use of your Couchbase Cluster(s),
under Couchbase's Enterprise or Community license agreements. 

* https://www.couchbase.com/license-agreement/[Enterprise License Agreement] -- this support level also applies to users of Capella Operational.
* https://www.couchbase.com/community-license-agreement/[Community License Agreement] -- this support level also applies to users of Capella Free Tier.


== Dependencies

Any dependencies may have their https://www.couchbase.com/legal/agreements#ThirdPartyComponents[own, separate licenses^].


== Documentation License

This documentation is copyright Couchbase Inc.
The docs' source is licensed under the Creative Commons https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en[CC-by-NC-SA^] license,
see https://github.com/couchbase/docs-sdk-{name_platform_lc}/blob/release/{sdk_dot_minor}/LICENSE[https://github.com/couchbase/docs-sdk-{name_platform_lc}/blob/release/{sdk_dot_minor}/LICENSE].

// It's painful to keep mis-spelling licence!
