= Search
:nav-title: Search Overview
:page-aliases: ROOT:full-text-search-overview


[abstract]

The _Search Service_ lets you create, manage, and query specially purposed _indexes_, defined on JSON documents within a Couchbase bucket.

== What is the Search Service?

The _Search Service_ provides extensive capabilities for _natural-language querying_: this allows special search-constraints to be applied to text-queries.
Results can be _scored_, to indicate match-relevancy; and result-sets ordered correspondingly.
_Conjunctive_ and _disjunctive_ searches can be performed, whereby common result-subsets from multiple queries can either be returned or omitted.

A full overview of the Search Service is provided in xref:server:fts:full-text-intro.adoc[The Search Service: Fundamentals].
This includes information on the principal features of Couchbase Search Service, its architecture, and the latest feature-additions.
Other information-sources include:

* xref:7.2@server:fts:fts-performing-searches.adoc[Performing Searches]: An explanation of the steps required to prepare for and perform Search.
* xref:7.2@server:fts:fts-searching-from-the-ui.adoc[Searching from the UI]: A brief introduction to the Search Service user interface provided by the Couchbase Web Console, with a step-by-step example of how to create a simple Search Index, and perform a search on it.
* xref:7.2@server:fts:fts-searching-with-the-rest-api.adoc[Searching with the REST API]: Basic examples of how Search is performed with REST, and pointers to more complex examples.
* xref:7.2@server:fts:fts-creating-indexes.adoc[Creating Indexes]: A full description of the index-creation facility provided by the Couchbase Web Console, with explanations of each component to be used, and illustrations of how indexes can be designed to include specific subsets of documents and their fields.
* xref:7.2@server:fts:fts-using-analyzers.adoc[Understanding Analyzers]: An explanation of _analyzers_, which are used to process the text to be included in Search Indexes.
* xref:7.2@server:fts:fts-queries.adoc[Queries]: A detailed account of available query types, response objects, and result-sorting options.


== Performing Search from the SDK

Couchbase SDKs provides an API for the support of Search querying.
A detailed example of performing Search queries from the SDK is provided in xref:howtos:full-text-searching-with-sdk.adoc[Searching from the SDK].

Note that to access Search, users require appropriate _roles_.
The role `fts_admin` must therefore be assigned to those who intend to create indexes; and the role `fts_searcher` to those who intend to perform searches.
For information on creating users and assigning roles, see the xref:7.1@server:learn:security/roles.adoc#search-admin[RBAC Roles page].

// Check about the roles required for search and for index creation, and link to the relevant documentation on that.

== Search from {sqlpp}

The search service can be accessed by xref:7.2@server:n1ql:n1ql-language-reference/searchfun.adoc[search functions in {sqlpp} Query] (formerly N1QL).
